Audio: Fix build error due to wakeup_source API's
Fix below implicit build error
"aov_trigger.c:256:2: error: implicit declaration of function 'wakeup_source_init'"

On latest kernel rebase from QC:
we see couple of wakeup_source API's are removed.

This fix replaces
1) wakeup_source_init(..) function with to wakeup_source_register(..)
2) wakeup_source_trash(..) function with to wakeup_source_unregister(..)

Change-Id: Ibd5ab4bff0a05f56981b50071f462e99d5b9841b